services:
  - type: web
    name: lamp-docker-cloud
    env: docker
    plan: free

    repo: https://github.com/AdrielMendez/lamp-docker-cloud
    branch: main

    dockerfilePath: Dockerfile
    dockerContext: .

    autoDeploy: true

    healthCheckPath: /
